name: Tamil OTT Auto Import

on:
  schedule:
    - cron: "0 6 * * *"   # runs daily at 06:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run JustWatch → Radarr Script
        env:
          RADARR_URL: ${{ secrets.RADARR_URL }}
          RADARR_API_KEY: ${{ secrets.RADARR_API_KEY }}
          RADARR_QUALITY_PROFILE_ID: "2"   # 1080p profile id in your Radarr
          RADARR_LANGUAGE_PROFILE_ID: "1"
        run: python main.py
