name: JustWatch to Radarr

on:
  schedule:
    - cron: "0 12 * * *"   # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Debug repo contents   # ✅ list files to confirm path
        run: ls -R

      - name: Run JustWatch to Radarr script
        env:
          RADARR_URL: ${{ secrets.RADARR_URL }}
          RADARR_API_KEY: ${{ secrets.RADARR_API_KEY }}
          RADARR_QUALITY_PROFILE_ID: "2"
          RADARR_LANGUAGE_PROFILE_ID: "1"
        run: python scripts/justwatch_to_radarr.py   # ✅ fixed path
